create table itemv2
(
    id        bigint generated by default as identity,
    itemname  varchar(255),
    price     int,
    quantity  int,
    imgpath   varchar(255),
    imgname   varchar(255)
);